/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Review {
  'comment' : [] | [string],
  'swapRequestId' : bigint,
  'rating' : bigint,
  'reviewee' : Principal,
  'reviewer' : Principal,
}
export interface Skill { 'name' : string }
export interface SwapRequest {
  'id' : bigint,
  'to' : Principal,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'sessionTime' : [] | [bigint],
  'from' : Principal,
  'skillWanted' : string,
  'skillOffered' : string,
}
export interface UserProfile {
  'skillsOffered' : Array<Skill>,
  'name' : string,
  'email' : string,
  'averageRating' : number,
  'location' : string,
  'skillsWanted' : Array<Skill>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptSwapRequest' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'findMatches' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMySwapRequests' : ActorMethod<[], Array<SwapRequest>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getReviewsForUser' : ActorMethod<[Principal], Array<Review>>,
  'getSwapRequestStatus' : ActorMethod<
    [bigint],
    { 'pending' : null } |
      { 'completed' : null } |
      { 'rejected' : null } |
      { 'accepted' : null }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[bigint, bigint], Array<UserProfile>>,
  'markSwapComplete' : ActorMethod<[bigint], undefined>,
  'rejectSwapRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsersBySkill' : ActorMethod<[string], Array<UserProfile>>,
  'sendSwapRequest' : ActorMethod<[Principal, string, string], bigint>,
  'submitReview' : ActorMethod<[bigint, bigint, [] | [string]], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, string, Array<Skill>, Array<Skill>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];