/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Skill = IDL.Record({ 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'skillsOffered' : IDL.Vec(Skill),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'averageRating' : IDL.Float64,
  'location' : IDL.Text,
  'skillsWanted' : IDL.Vec(Skill),
});
export const SwapRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'sessionTime' : IDL.Opt(IDL.Int),
  'from' : IDL.Principal,
  'skillWanted' : IDL.Text,
  'skillOffered' : IDL.Text,
});
export const Review = IDL.Record({
  'comment' : IDL.Opt(IDL.Text),
  'swapRequestId' : IDL.Nat,
  'rating' : IDL.Nat,
  'reviewee' : IDL.Principal,
  'reviewer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptSwapRequest' : IDL.Func([IDL.Nat, IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'findMatches' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySwapRequests' : IDL.Func([], [IDL.Vec(SwapRequest)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getReviewsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getSwapRequestStatus' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'rejected' : IDL.Null,
          'accepted' : IDL.Null,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(UserProfile)], ['query']),
  'markSwapComplete' : IDL.Func([IDL.Nat], [], []),
  'rejectSwapRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsersBySkill' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'sendSwapRequest' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Vec(Skill)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Skill = IDL.Record({ 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'skillsOffered' : IDL.Vec(Skill),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'averageRating' : IDL.Float64,
    'location' : IDL.Text,
    'skillsWanted' : IDL.Vec(Skill),
  });
  const SwapRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'sessionTime' : IDL.Opt(IDL.Int),
    'from' : IDL.Principal,
    'skillWanted' : IDL.Text,
    'skillOffered' : IDL.Text,
  });
  const Review = IDL.Record({
    'comment' : IDL.Opt(IDL.Text),
    'swapRequestId' : IDL.Nat,
    'rating' : IDL.Nat,
    'reviewee' : IDL.Principal,
    'reviewer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptSwapRequest' : IDL.Func([IDL.Nat, IDL.Int], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'findMatches' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySwapRequests' : IDL.Func([], [IDL.Vec(SwapRequest)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getReviewsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getSwapRequestStatus' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'rejected' : IDL.Null,
            'accepted' : IDL.Null,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'markSwapComplete' : IDL.Func([IDL.Nat], [], []),
    'rejectSwapRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsersBySkill' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendSwapRequest' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Vec(Skill)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };